redhat-developer/web-terminal-operator

manifests/web-terminal.clusterserviceversion.yaml

This PR adds in watch for webhooks into the csv. Taken from: https://github.com/devfile/devworkspace-operator/pull/136

Update role in csv file to add in watch for webhooks

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/a_question.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md

This PR adds in an initial version of the issue template. If theres anything you guys thing I should change/add let me know!

Add initial version of the issue template

---

.github/workflows/dockerimage-next.yml
Makefile
README.md

Set up github action to build bundle and index from master
https://issues.redhat.com/browse/WTO-24
it's tested in https://github.com/redhat-developer/web-terminal-operator/runs/882142712

Set up github action to build bundle and index from master

---

.github/workflows/dockerimage-next.yml
Makefile
README.md

Align bundle image name we have for osbs and upstream.
N/A

Align bundle image name we have for osbs and upstream

---

manifests/web-terminal.clusterserviceversion.yaml

Minor fix for some of the wording in our csv's description; I noticed this while testing out the operator install flow.

Fix slightly clumsy wording in csv description

---

.github/workflows/dockerimage-next.yml
Dockerfile
Makefile
README.md
container.yaml
manifests/web-terminal.clusterserviceversion.yaml
metadata/annotations.yaml

This PR builds on https://github.com/redhat-developer/web-terminal-operator/pull/22 (so that one should be merged first). It syncs parts of the downstream repo (Dockerfile, container.yaml, and metadata/*) with this branch. That way source syncing will be a lot easier.
Part of https://issues.redhat.com/browse/WTO-23

V1.0.x downstream sync

---

manifests/web-terminal.clusterserviceversion.yaml

This PR adds a known issues field linking to any issues users might run into

Add known issues field

---

manifests/web-terminal.clusterserviceversion.yaml

This PR fixes the spacing of known issues so that it's separate from the uninstall instructions

Fix spacing of known issues

---

manifests/web-terminal.clusterserviceversion.yaml

Port known issues to v1.0.x branch

Add known issues v1.0.x

---

manifests/web-terminal.clusterserviceversion.yaml

This PR updates images to use the x.y.z. This has been down in downstream a long time ago, just need to bring the change upstream

Update images to use x.y.z versioning

---

Makefile
manifests/controller.devfile.io_components_crd.yaml
manifests/controller.devfile.io_workspaceroutings_crd.yaml
manifests/workspace.devfile.io_devworkspaces_crd.yaml
update-dependencies.sh

Updates CRDs to v1alpha1.
There are generated changes I've ignored:
related PR https://github.com/devfile/devworkspace-operator/pull/146

Update CRDs to v1alpha1

---

Makefile
README.md

Clean up and improve README.md.

Clean up README.md for readability.

---

README.md
manifests/web-terminal.clusterserviceversion.yaml

Add a quick note about compatibility (OpenShift 4.5.3 or higher) to end-user visible docs.

Add note about OpenShift version compatibliity to README and CSV

---

manifests/web-terminal.clusterserviceversion.yaml

This PR updates to version 1.0.1
Potential fix for our issues with the release

Update manifest to be v1.0.1

---

controller.Jenkinsfile
metadata.Jenkinsfile

This PR makes the jenkinsfiles grab the scripts from v1.0.x since we no longer use master

Update the referenced bootstrap-sync.sh

---

.github/workflows/dockerimage-next.yml

Fix the default branch in Github Actions

Fix the default branch in Github Actions

---

CHANGELOG.md

This PR updates the changelog to include 1.2 information

Update changelog with 1.2 information

---

Makefile
README.md
update-dependencies.sh

Add small improvements & fixes
N/A
Tested, but changes are pretty clear.

Add small improvements & fixes

---

README.md

Add reference to WTO Jira
It fixes https://issues.redhat.com/browse/WTO-97

Add reference to WTO Jira

---

manifests/web-terminal.clusterserviceversion.yaml

This PR makes web terminal 1.3 replace web terminal v1.2.1 instead of v1.2.0. I think this might be a cause of one of my issues downstream and hopefully this will fix it

Update replaces from v1.2.0 to v1.2.1 since v1.2.1 is released

---

manifests/web-terminal.clusterserviceversion.yaml

Just a couple of small things I found in the manifests. I don't think we need the suggested namespace anymore because we aren't doing single namespace anymore and I might as while update the createdAt time :wink:

Manifest tweaks

---

build/dockerfiles/controller.Dockerfile
main.go
pkg/config/config.go
pkg/config/constants.go
pkg/webterminal/defaults.go
pkg/webterminal/exec.go
pkg/webterminal/tooling.go

Update license years now that it's 2022

Update license years for 2022

---

.github/CODEOWNERS
build/dockerfiles/Dockerfile
manifests/web-terminal.clusterserviceversion.yaml

Update owners to @amisevsk and @ibuziuk 
N/A
N/A

Update owners to amisevsk and ibuziuk

---

README.md
build/scripts/build_index_image.sh

Update readme to include `make build_controller_image` and fixup using default images in `build_index_image.sh`
N/A
N/A

Update readme to include building controller image, fixup index script

---

manifests/web-terminal.clusterserviceversion.yaml

Removes `-dev` from package name for 1.6.0 release.
N/A

Fix package+version name for 1.6

---

.github/workflows/pr-check.yml
build/dockerfiles/controller.Dockerfile
go.mod

Update base images used in dockerfile
N/A

Update base images in dockerfile

---

CHANGELOG.md
build/dockerfiles/Dockerfile
build/dockerfiles/controller.Dockerfile
manifests/web-terminal.clusterserviceversion.yaml

Prepare for WTO 1.8 release
* Update changelog, CSV version
* Update base images for controller build
* Update minimum OpenShift version annotation
N/A

Prepare for 1.8 release

---

.github/workflows/pr-check.yml
CHANGELOG.md
build/dockerfiles/Dockerfile
build/dockerfiles/controller.Dockerfile
go.mod
manifests/web-terminal.clusterserviceversion.yaml

* Update changelog, CSV version
* Update base images for controller build
* Update minimum OpenShift version annotation
N/A

Prepare for WTO 1.9 release

---

.github/CODEOWNERS
.github/workflows/dockerimage-next.yml
.github/workflows/pr-check.yml
build/dockerfiles/Dockerfile
build/dockerfiles/controller.Dockerfile
main.go
pkg/config/config.go
pkg/config/constants.go
pkg/webterminal/defaults.go
pkg/webterminal/exec.go
pkg/webterminal/tooling.go

Update copyright years for 2024 and add @AObuchow to codeowners
N/A

Update copyright years and codeowners

---

.github/CODEOWNERS
build/dockerfiles/Dockerfile
manifests/web-terminal.clusterserviceversion.yaml

Transfering repo ownership to @dkwon17 :pray: 
:wave: 
N/A
N/A

Remove aobuchow from code owners, update owner to dakwon

---

.github/workflows/dockerimage-next.yml
.github/workflows/pr-check.yml

Updates actions/checkout and actions/cache to v4

Update actions/checkout and actions/cache to v4
