redhat-developer/web-terminal-operator

- .gitignore
- Makefile
- collect-sources.sh
- manifests/edit-workspaces-cluster-role.yaml
- manifests/view-workspaces-cluster-role.yaml
- manifests/web-terminal.clusterserviceversion.yaml
- update-dependencies.sh
This PR collects a number of improvements to the CSV generation process.
Commit by commit:
- ce40236 - Move downloading devworkspace-operator and apis to separate script since Makefiles are tedious to write. This new script downloads both repos sparsely, and copies all files into another folder, `devworkspace-dependencies`, which is to be used for CSV generation. 
- Merging the folders allows us to generate the CSVs directly without the need for manually adding a section for the devworkspace CRD
- Sparse checkout of the devworkspace-operator repo means we no longer need to filter out irrelevant files from the generated CSV
- 5a1292d - Cleanup makefile and script from code review. Improves logging in the download script and removes `set -x`, which was only set for my debugging.
- f0d4230 - …
> Improve manifest generation

- manifests/web-terminal.clusterserviceversion.yaml
This PR regenerates manifests after switching to devworkspace naming. 
It depends on upstream PR https://github.com/devfile/devworkspace-operator/pull/125
It's done for https://github.com/eclipse/che/issues/17179
```
export BUNDLE_IMG=quay.io/sleshche/che-workspace-bundle:devworkspace-name
export INDEX_IMG=quay.io/sleshche/che-workspace-operator-index:devworkspace-name
make olm_install_local
```
> Regenerate manifests after switching to devworkspace naming

- manifests/web-terminal.clusterserviceversion.yaml
Updates manifests for https://github.com/devfile/devworkspace-operator/pull/126. Generated by manually checking out the PR branch in `devworkspace-operator` and regenerating the files using `make gen_terminal_csv`.
Do not merged until https://github.com/devfile/devworkspace-operator/pull/126 is merged.
related to https://github.com/eclipse/che/issues/16967
related to https://github.com/eclipse/che/issues/16980
Tested using `make build install` on `crc`
> Update manifests for PR #126 in devworkspace operator

- .gitignore
- Makefile
This PR adds a new command called export that exports all the bundles in the web terminal index with the name web-terminal into a folder called exported-manifests.
This is going to be more useful later down the line when we have multiple bundles inside of the index and we want to double-check that all bundles are loaded into the index.
Ran `make export` and checked that all bundles were loaded
> Add export command for helping to verify the bundles in your index

- manifests/web-terminal.clusterserviceversion.yaml
- manifests/workspace.devfile.io_devworkspaces_crd.yaml
This PR updates manifests after a few changes in dependencies:
- Use wto-related images from quay.io/wto https://github.com/devfile/devworkspace-operator/pull/133
- VolumeMount should require Volume component definition https://github.com/devfile/kubernetes-api/pull/101
- add starterProject fields  https://github.com/devfile/kubernetes-api/pull/92
No regression is expected
> Update manifests after a few changes in dependencies

- manifests/web-terminal.clusterserviceversion.yaml
This PR sets quay.io/wto/xxx:1.0 images and removes nightly.
It also removes nightlies and dev related images since they are already removed from internal registry: http://pkgs.devel.redhat.com/cgit/containers/web-terminal/tree/internal-registry/redhat-developer/web-terminal/4.5.0?h=web-terminal-1.0-rhel-8
So, in that way, we can test Operator very similar to what we'll have after release.
I know that these changes will be overridden after `make gen_terminal_csv` but the base branch is v1.0.x which is not expected to be changed, right?
N/A
```
export BUNDLE_IMG=quay.io/sleshche/che-workspace-bundle:v1.0.0
export INDEX_IMG=quay.io/sleshche/che-workspace-operator-index:v1.0.0
make install
kc apply -f ../devworkspace-operator/samples/cloud-shell.yaml
kc get devworkspace
kubectl logs …
```
> Use wto 1.0-x images

- Makefile
- manifests/web-terminal.clusterserviceversion.yaml
This PR improves operator uninstalling:
1. `make uninstall` does not fail and clean up other resources if CRDs are removed by someone else.
I believe for Operator description that is not critical since admins are supposed to copy/paste section by section.
2. Remove namespace while removing the cluster role to avoid warning that it's not a namespace-scoped object.
3. Does not fail if webhook server deployment is already removed.
^ I thought about if there is any sense to fail and it may - like it helps us to make sure that we remove right objects and if we remove objects and forget about that here - it will be easier to figure it out... So, as an alternative I see we have two makefile rules: uninstall - fail if not found, purge  - try to remove everything without failing ( I got it from …
> Improve operator uninstalling

- Makefile
- manifests/web-terminal.clusterserviceversion.yaml
This PR:
-  removes ignore-not-found on uninstall: I think it could help us to discover object naming inconsistency ( object is renamed in the code, but not in uninstall instructions). Since admins will copy/paste commands into terminal (I suppose) removing --ignore-not-found should produce an error but not fail whole uninstalling procedure even if a couple of commands are copied at the same time:
- introduces purge make target: allows to clean objects up if we're sure that there is no bug and uninstall failure caused by interrupted uninstalling or removing some parts manually.
I tried make `uninstall` and `purge` reuse internal target like `_uninstall` with arguments like `REMOVE_DEVWORKSPACE_CRD` (true/false), `DELETE_OPTIONS`("", "--ignore-not-found") but I did not manage to archive …
> Don't use ignore-not-found on uninstall and introduce purge make target

- Makefile
- manifests/web-terminal.clusterserviceversion.yaml
Cherry-pick changes related to uninstallation procedure:
https://github.com/redhat-developer/web-terminal-operator/pull/16
https://github.com/redhat-developer/web-terminal-operator/pull/17
It's mainly done to align make uninstall rule with documentation and a few fixes - like remove namespace for cluster-scope objects.
It's my first time when I tried successfully use `git rebase --onto` =)
N/A
I haven't tested it manually but I'm going to before merging.
> Cherry-pick changes related to uninstallation procedure

- Makefile
We construct image digests using bash string processing, which requires
the image to be set in an environment varible. However, in the makefile,
there are default values for variables that don't get propagated to the
environment, meaning make install and make build fail when those
default values are used.
Instead, we explicitly set the environment before constructing the
digest.
Run `make install`/`make build` with and without `INDEX_IMG`/`BUNDLE_IMG` set.
> Fix issue where unset env vars break makefile

- Makefile
Fix the check for whether skopeo is installed; somehow it got switched to checking for kubectl instead
Fixes #32
> Fix skopeo check in Makefile

- Makefile
PR fixes an issue where _check_skopeo_installed should use skopeo not kubectl. cherry-picked to v1.0.x
> [cherry-pick] Check for skopeo not kubectl

- Makefile
Signed-off-by: jpinkney <josh.pinkney@mail.utoronto.ca>
PR fixes an issue where _check_skopeo_installed should use skopeo not kubectl
> Check for skopeo not kubectl 

- Makefile
- catalog-source.yaml
- manifests/controller.devfile.io_components_crd.yaml
- manifests/controller.devfile.io_workspaceroutings_crd.yaml
- manifests/workspace.devfile.io_devworkspaces_crd.yaml
- operator-subscription.yaml
- update-dependencies.sh
Port changes from v1.0.x and rename catalog source.
N/A
```
make install
make uninstall
make unregister_catalogsource
```
> Port changes from v1.0.x and rename catalog source

- README.md
- manifests/web-terminal.clusterserviceversion.yaml
Cherry-pick of https://github.com/redhat-developer/web-terminal-operator/pull/38 to `v1.0.x`
Add a quick note about compatibility (OpenShift 4.5.3 or higher) to end-user visible docs.
> Add note about OpenShift version compatibliity to README and CSV

- Dockerfile
This PR removes the no longer needed com.redhat.delivery.appregistry label
> Remove com.redhat.delivery.appregistry from Dockerfile

- manifests/web-terminal.clusterserviceversion.yaml
This PR removes `replaces: web-terminal.v1.0.0` since 1.0.1 will be our first release
> Remove replaces web-terminal.v1.0.0 since it won't be present in the index

- Makefile
This PR introduces a new env var LATEST_INDEX_IMG that stores the last released version of the index (in this case v1.0.1). We need this because when you have `replace: web-terminal.v1.0.1` in the csv and `web-terminal.v1.0.1` is not available when creating a new index then that step will fail.
https://github.com/redhat-developer/web-terminal-operator/issues/50
Used `make build` and it now successfully works
> Introduce LATEST_INDEX_IMG env var to fix next CI build

- Makefile
- operator-subscription.yaml
It bumps versions to 1.0.2 to fix `make install` & `make uninstall` commands.
It's a quick fix but we will need to provide a more flexible solution that auto-evaluates the version, something like https://github.com/redhat-developer/web-terminal-operator/pull/52 but working on MacOS as well )
N/A
1. `make install`
2. Make sure operator is installed.
3. `make uninstall`
4. Make sure operator is uninstalled.
> Bump versions to 1.0.2

- content_sets.yml
- content_sets_rhel8.repo
This PR adds in content sets that are needed for our next release of the web terminal operator. I'm not exactly sure how to verify it without throwing it into the pkg.devel repos. For now I've just copied them from web-terminal-tooling.
FWIW the previous cvp results are here: http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-product-test/web-terminal-operator-container-1.0.1-1/fd2f6fdf-ffad-4d04-94e3-6b08f092e044/sanity-tests-optional-results.json
> Add content sets for web terminal operator

- Makefile
This PR fixes removing of WTO CSV.
Note that it's made against v1.0.x since we're going to deprecate master.
N/A
1. `make install`
2. wait until WTO is installed
3. `make uninstall`
4. Make sure that WTO is not displayed as installed operator on Console.
> Fix removing of WTO CSV

- Makefile
After upgrading to the 1.0.1 binary needed for devworkspace-controller, I became unable to build the bundle because they shifted commands around (operator-sdk bundle create became operator-sdk generate bundle). Instead of maintaining 2 different versions of operator-sdk locally this PR makes it so that you can use `make build` without operator-sdk installed.
I found out that you can just build the bundle using the Dockerfile in the root. This is actually suggested when you run: `operator-sdk generate bundle`:
```bash
$ operator-sdk bundle validate ./bundle
$ docker build -f bundle.Dockerfile -t $BUNDLE_IMG .
Sending build context to Docker daemon  42.33MB
Step 1/9 : FROM scratch
```
(bundle.Dockerfile is essentially the same Dockerfile …
> Replace operator-sdk bundle create with docker build

- Makefile
- manifests/web-terminal.clusterserviceversion.yaml
- operator-subscription.yaml
- productization/jenkinsfiles/metadata.Jenkinsfile
This PR fixes `make install` which is currently broken since WTO pull the next DWO which depends on v1alpha2 which are not in CSV yet.
Note that v1alphax container is built manually and if we get any update on DWO, we need to set up github action to build it.
> Make next WTO depends on v1alphax DWO

- .github/workflows/dockerimage-next.yml
This PR fixes fixes build of next dockerimage.
There were two issues:
1. ::add-path:: is deprecated https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
2. setup-k8s-operator-sdk is broken https://github.com/shivanshs9/setup-k8s-operator-sdk/issues/4
N/A
The test run https://github.com/redhat-developer/web-terminal-operator/runs/1861486269?check_suite_focus=true
> Fix build of next dockerimages

- dev-scripts/webterminal-localhost.sh
So, this PR introduces `official` script (earlier we had gists :-D) which allows to do some tricks on localhost/openshift-console side to web terminal working on localhost.
It's supposed that users run this script from openshift/console project, it's easier after `--install` is done.
The latest I did - install the script (Ubuntu, not sure if it's going to work on MacOS) and got web terminal working on localhost
> Initial implementation for terminal on localhost

- manifests/web-terminal.clusterserviceversion.yaml
This PR re-adds the `RELATED_IMAGE_web_terminal_tooling` env variable that was accidentally removed. Apparently, when I switched the default branch from master to main I forgot to change the branch protection rules so when I accidentally pushed to main it went through :facepalm:. The reason why the other env variables were removed was because in CPaaS we don't have a way of just using yq to filter out env variables we don't need. Instead, it's easiest for me to just have the env variables defined that we want in the product. Otherwise, we'd have to wait for CPaaS to support that feature
> Re-add tooling

- README.md
This PR add note how to configure custom default image.
It's different for 1.2 and earlier and 1.3 and future due https://github.com/devfile/devworkspace-operator/pull/319
We may want to backport that fix into 1.2.1 but I'm not sure it worths time.
It depends on https://github.com/devfile/devworkspace-operator/pull/319
I executed the shared command, and checked that the desired container is started as default for WTO 1.2 and my fresher with https://github.com/devfile/devworkspace-operator/pull/319 included :
```
export BUNDLE_IMG=quay.io/sleshche/che-workspace-bundle:custom-image
export INDEX_IMG=quay.io/sleshche/che-workspace-operator-index:custom-image
```
> Add note how to configure custom default image

- dev-scripts/webterminal-localhost.sh
- manifests/web-terminal.clusterserviceversion.yaml
It makes WTO repo use the latest terminal plugin which is available starting from WTO 1.2.1.
It's WIP since it depends on OpenShift Console changes, otherwise devscript won't work https://github.com/openshift/console/pull/8795
> Use latest WebTerminal plugin instead of 4.5.0

- Makefile
In some specific cases the command can perform too long. For example:  when we try to get **Index Didgest** from a IIB image. For instance: invokation command like `skopeo inspect docker://registry-proxy.engineering.redhat.com/rh-osbs/iib:77245 --debug` can take about 20-30 minutes.
**Screencast:**
As alternative solution we can pull the image locally and get the Didgest with jg. It can decrease a gettin the image didgest. This PR add new target to the Makefile
Has been checked on local crc instance
> Add an ability to configure digest evaluation method

- .github/workflows/dockerimage-next.yml
- .github/workflows/pr-check.yml
- Makefile
- README.md
- build/dockerfiles/controller.Dockerfile
- build/makefiles/controller.mk
- build/makefiles/deployment.mk
- go.mod
This PR provides the following changes:
- fix controller image and make github workflow build the next tag;
- return back target for uninstalling WTO 1.2;
- ~~disable an ability to install operator in All namespace mode, since it's redundant in our case at this point, and it's the time we can migrate to newer preferable way;~~ moved to https://github.com/redhat-developer/web-terminal-operator/pull/82
- add pr check to verify go sources and controller images;
- upgrade controller to go 1.15 and use newer way to install go in ubi image suggested in https://github.com/eclipse/che/issues/19762;
It's for https://issues.redhat.com/browse/WTO-101
> several improvements and fixes after switching WTO to be dependent on DWO

- build/dockerfiles/Dockerfile
- manifests/web-terminal.clusterserviceversion.yaml
- metadata/annotations.yaml
- operator-subscription.yaml
DevWorkspace operator which is a dependency for WTO, is going to be All namespaces mode.
So, it forces WTO to be all namespaces mode, even though WTO does not need to watch all namespaces ATM.
It's agreed with OLM team and they told all operators are moving to all-namespace mode, so it won't be possible to install the same operator twice.
Also, this PR has a dedicated commit to change channel from alpha to fast, it's done due:
- this way we force users to manually uninstall WTO from a new channel;
- fast is name recommended by OLM https://olm.operatorframework.io/docs/best-practices/channel-naming/#naming for 
> Released, supported operators which are still being monitored to assess stability/quality prior to promoting them as stable. Generally used by early adopters or for testing in …
> Do not support single namespace install mode

- manifests/web-terminal.clusterserviceversion.yaml
This PR removes our example from alm-examples because it causes bundle verification downstream to error with: `time="2021-06-14T21:15:01Z" level=error msg="Error: Value workspace.devfile.io/v1alpha2, Kind=DevWorkspace: example must have a provided API"`
> Remove examples from alm-examples

- docs/uninstall.md
- manifests/web-terminal.clusterserviceversion.yaml
Update WTO csv description for 1.3.0. I think we should probably avoid attempting to document the uninstall process within the description itself, as the process is going to be different between version 1.2.1 and 1.3.0. I've started an `uninstall.md` to begin documenting this, though it should be surfaced in a more official way.
There are a couple of TODO links in the descriptions, as I'm not sure if we should e.g. include a link to the [OpenShift docs](https://docs.openshift.com/container-platform/4.7/web_console/odc-about-web-terminal.html#odc-uninstalling-web-terminal_odc-about-web-terminal), since those are version-specific and will be out of date on 4.8.
N/A
> Update operator description for 1.3.0 and attempt to document uninstall

- manifests/web-terminal.clusterserviceversion.yaml
Update the link used for the uninstall steps to point at the OpenShift docs: https://docs.openshift.com/container-platform/latest/web_console/odc-about-web-terminal.html
I've set it to point at the latest version, to avoid issues of out-of-date links on future releases.
> Update uninstall steps in description to link to OpenShift docs.

- pkg/config/constants.go
- pkg/webterminal/exec.go
- pkg/webterminal/tooling.go
Adapts WTO to PR https://github.com/devfile/devworkspace-operator/pull/466 (allow WTO dwts to be read in all namespaces).
Should not be merged until https://github.com/devfile/devworkspace-operator/pull/466 is merged.
Related to https://github.com/devfile/devworkspace-operator/issues/403
Should be no change in functionality.
> Add annotation to Web Terminal DWTs to allow reading anywhere

- pkg/config/constants.go
- pkg/webterminal/exec.go
- pkg/webterminal/tooling.go
Apply a common label (shared with web terminal instances themselves) to DevWorkspaceTemplates created by the Web Terminal Operator in order to make their removal easier.
Helps with documenting how to uninstall the operator, as we can remove these templates in a targetted way.
Should be no changes functionally.
> Label DevWorkspaceTemplates to allow easier removal

- .github/workflows/dockerimage-next.yml
- Makefile
- build/scripts/build_index_image.sh
Hopefully fixes the "Next Dockerimages" GH action, which has been failing for awhile due to the `replaces` field in the CSV. This change introduces a script derived from the [devworkspace operator](https://github.com/devfile/devworkspace-operator/blob/a6c27fed5432d8dc28ac66861c33e54bc032b421/build/scripts/build_index_image.sh) that builds the bundle + index a little more cleanly.
I also removed a couple of vars from the Makefile that seem to be unused.
Tested by running `make build` locally.
> Fix issue where catalog cannot be built due to replaces field in CSV

- pkg/webterminal/exec.go
Set timeout for web terminals through an environment variable in the web-terminal-exec plugin rather than through the automatically provisioned DEVWORKSPACE_IDLE_TIMEOUT environment variable. This allows
the timeout for individual terminals to be changed without overriding the timeout for all DevWorkspaces
The main reason to update the idle timeout currently is that the bash history is erased when a Web Terminal is idled. By setting a longer duration, a session could continue for e.g. a full work day.
We've had a number of requests for how to increase the web terminal timeout, which normally requires editing the DevWorkspace Operator config or the `web-terminal-exec`. With these changes, it's easy to override the timeout for individual web terminals in a persistent way.
Start a web …
> Decouple web terminal idle timeout from DevWorkspace idle timeout

- dev-scripts/webterminal-localhost.sh
Fixes the `webterminal-localhost.sh` script to make testing the OpenShift Console side of the Web Terminal Operator functionality easier. Required changes:
* Kubernetes 1.22 and up no longer stores serviceaccount tokens in secrets by default. To work around this, we read the serviceaccount token from the pod directly when emulating in-cluster functionality
* The `sed` replacements for patching the Console frontend/backend were out of date; on the frontend we can no longer rely on the web-terminal-dev plugin, and instead have to disable TLS directly in the existing web-terminal-exec plugin via overrides. On the backend, we need to be careful about managing the URL to handle `https` and the path added for basic routing
* Thing I was stuck on forever: if you try to POST to a route that uses …
> Fix localhost script

- CHANGELOG.md
- manifests/web-terminal.clusterserviceversion.yaml
Sets up the repo to have current version `v1.6.0-dev`.
I've created a [release branch for the 1.5.x stream](https://github.com/redhat-developer/web-terminal-operator/tree/1.5.x), so it makes sense to set the version to 1.6.0-dev in main
> Set version to v1.6.0-dev in preparation for 1.6.0 release

- CHANGELOG.md
Updates tooling versions in changelog to account for https://github.com/redhat-developer/web-terminal-tooling/pull/48 and adds line for https://github.com/redhat-developer/web-terminal-tooling/pull/40
N/A
> Update changelog with new versions and note about bash history

- README.md
Reorganize the README.md to
* Clarify details of configuring default images used for web terminals
* Improve language/clarity
* Reorganize to emphasize more useful information (how to configure terminals) rather than how to install manually.
N/A
N/A
> Reorganize readme to emphasize more useful information and clean up

- manifests/web-terminal.clusterserviceversion.yaml
See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/web_console/odc-about-web-terminal#odc-using-web-terminal_odc-about-web-terminal .
The docs mention web terminal in lower case.
> Update CSV casing of web terminal to match documentation

- Makefile
- pkg/webterminal/exec.go
- pkg/webterminal/tooling.go
Updates images for templates with `web-terminal.redhat.com/unmanaged-state: "true"` if the image in the template comes from the default image repository.
This ensures that fixes/updates are still applied to WTO installs in clusters even if an admin has decided to e.g. modify resource requests/limits.
If the image in the template comes from another repository (e.g. a custom-built tooling image) no changes are made.
Also updates the Makefile:
* Drop some environment variables we no longer use
* Fix `make help` not printing all available rules
Resolves https://issues.redhat.com/browse/WTO-209
To test:
1. Install Web Terminal Operator in a cluster
2. Update `web-terminal-tooling` and `web-terminal-exec` DevWorkspaceTemplates to have `web-terminal.redhat.com/unmanaged-state: "true"` …
> Update images in templates even if state is unmanaged

- .github/workflows/pr-check.yml
- CHANGELOG.md
- build/dockerfiles/Dockerfile
- build/dockerfiles/controller.Dockerfile
- manifests/web-terminal.clusterserviceversion.yaml
- Updates the changelog, refer to https://github.com/redhat-developer/web-terminal-tooling/pull/69 for tooling version updates
- Updates CSV version to WTO 1.10
- Updates base images for controller build
- Updates minimum OpenShift version annotation to OpenShift 4.15
Testing requires an OpenShift 4.15 cluster.
I've built the controller, index and bundle images from this PR and pushed them to `quay.io/aobuchow/wto-controller:1.10`, `quay.io/aobuchow/wto-bundle:1.10` & `quay.io/aobuchow/wto-index:1.10` respectively.
The accompanying WTO tooling image (built from this [PR](https://github.com/redhat-developer/web-terminal-tooling/pull/69)) has also been pushed to `quay.io/aobuchow/wto-tooling:1.10`.
To test the images, set the `WTO_IMG`,  `BUNDLE_IMG` & `INDEX_IMG` environment variables to …
> Prepare for WTO 1.10 release

- CHANGELOG.md
Adds a note to the 1.10 release notes/changelog about https://github.com/redhat-developer/web-terminal-operator/issues/162 so that users can easily find the relevant bug and see if it has been resolved.
Part of https://github.com/redhat-developer/web-terminal-operator/issues/162 & 1.10 release process
n/a, documentation change
> Add kubeadmin terminal creation bug to known issues for 1.10

- Makefile
Some rules in the Makefile have empty instructions (for example, _reset_controller_image, _select_controller_image), rendering these rules unusable. This pull request reinstates these commands with minor modifications: _select_controller_image now allows applying any controller image to the CSV defined in the WTO_IMG variable, facilitating more than just toggling between quay.io/wto/web-terminal-operator-index:next and quay.io/wto/web-terminal-operator-index:latest as was previously the case. Additionally, _reset_controller_image can revert any registry reference back to the default image based on quai.
A new rule has also been introduced `build_custom_iib_image`, enabling the building and pushing of custom IIb images from the repository. This is particularly useful for verifying new …
> Fix and restore some lost commands in the Make file

- .github/workflows/pr-check.yml
- CHANGELOG.md
- build/dockerfiles/Dockerfile
- build/dockerfiles/controller.Dockerfile
- manifests/web-terminal.clusterserviceversion.yaml
- Update changelog, refer to https://github.com/redhat-developer/web-terminal-tooling/pull/71 for tooling version updates
- Update CSV version to WTO 1.11
- Update base images for controller build to UBI9
- Updates minimum OpenShift version annotation to OpenShift 4.16
n/a
Testing requires an OpenShift 4.16+ cluster. I recommend OpenShift 4.17, since the [backport to fix using kubeadmin with WTO](https://github.com/redhat-developer/web-terminal-operator/issues/162#issuecomment-2206400246) has not been merged to OpenShift 4.16 yet. 
From the root of this repo, you should be able to set the appropriate environment variables to point to your quay repo's and install WTO built from this PR:
```bash
export WTO_IMG=quay.io/<user>/wto-controller:1.11 && \
export …
```
> Prepare for WTO 1.11 release

- CHANGELOG.md
Mentions the removal of the odo CLI from the web terminal tooling image. 
odo does not currently support RHEL9 (and consequently, UBI9) based images. Since WTO 1.11 is based on UBI9, we are removing odo from the tooling image for the time being (see https://github.com/redhat-developer/web-terminal-tooling/pull/72).
odo can still be added to a custom web terminal tooling image by users if desired, see https://issues.redhat.com/browse/WTO-298 for more details.
https://issues.redhat.com/browse/WTO-298
n/a
> Mention removal of odo cli from 1.11 release notes

- .github/workflows/pr-check.yml
- CHANGELOG.md
- build/dockerfiles/Dockerfile
- build/dockerfiles/controller.Dockerfile
- manifests/web-terminal.clusterserviceversion.yaml
- Update changelog, refer to https://github.com/redhat-developer/web-terminal-tooling/pull/73 for tooling version updates
- Update CSV version to WTO 1.12
- Update base images used in controller Dockerfile 
- Updates minimum OpenShift version annotation to OpenShift 4.17
- Bumps go version in pr-check workflow to go v1.21.13
n/a
Testing requires an OpenShift 4.17+ cluster.
From the root of this repo, you should be able to set the appropriate environment variables to point to your quay repo's and install WTO built from this PR:
```bash
export WTO_IMG=quay.io/<user>/wto-controller:1.12 && \
export INDEX_IMG=quay.io/<user>/wto-index:1.12 && \
export BUNDLE_IMG=quay.io/<user>/wto-bundle:1.12
make build_custom_iib_image
make register_catalogsource 
```
WTO 1.12 should be installed (and …
> Prepare for WTO 1.12 release 

- .github/workflows/pr-check.yml
- build/dockerfiles/controller.Dockerfile
- build/scripts/build_index_image.sh
- go.mod
- go.sum
* Updates project to use go version 1.23
* Uses skopeo to get the image digest when building index image, instead of podman
https://github.com/redhat-developer/web-terminal-operator/issues/178
The `golang.org/x/net` dependency is quite outdated for this repository: https://github.com/redhat-developer/web-terminal-operator/blob/b135f1a2642cce856c6bf40d6abc2431ba505e67/go.mod#L42
The version of go needs to be updated to 1.23 to merge this update: https://github.com/redhat-developer/web-terminal-operator/pull/179.
Version `golang.org/x/net` 0.23 is susceptible to this CVE: https://access.redhat.com/security/cve/cve-2024-45338
After logging into an OpenShift cluster, run:
```
export WTO_IMG=quay.io/<user>/wto-controller:next && \
export INDEX_IMG=quay.io/<user>/wto-index:next && \
export …
```
> Update go 1.23

- CHANGELOG.md
- build/dockerfiles/Dockerfile
- build/dockerfiles/controller.Dockerfile
- manifests/web-terminal.clusterserviceversion.yaml
Updates the project for the WTO 1.13 release
Update changelog, refer to https://github.com/redhat-developer/web-terminal-tooling/pull/76 for tooling version updates
Update CSV version to WTO 1.13
Update base images used in controller Dockerfile
Updates minimum OpenShift version annotation to OpenShift 4.18
Testing requires an OpenShift 4.18+ cluster.
From the root of this repo, set the appropriate environment variables to point to your quay repo's and install WTO built from this PR:
```
export WTO_IMG=quay.io/<user>/wto-controller:1.13 && \
export INDEX_IMG=quay.io/<user>/wto-index:1.13 && \
export BUNDLE_IMG=quay.io/<user>/wto-bundle:1.13
make build_custom_iib_image
make register_catalogsource 
```
WTO 1.13 should be installed (and viewable on the Installed Operators page of the …
> Prepare for WTO 1.13 release

- CHANGELOG.md
- build/dockerfiles/Dockerfile
- build/dockerfiles/controller.Dockerfile
- manifests/web-terminal.clusterserviceversion.yaml
Updates the changelog, CSV, dockerfiles for the 1.14 release.
Testing requires an OpenShift 4.19+ cluster.
From the root of this repo, set the appropriate environment variables to point to your quay repo's and install WTO built from this PR:
```
export WTO_IMG=quay.io/<user>/wto-controller:1.14 && \
export INDEX_IMG=quay.io/<user>/wto-index:1.14 && \
export BUNDLE_IMG=quay.io/<user>/wto-bundle:1.14
make build_custom_iib_image
make register_catalogsource 
```
WTO 1.14 should be installed (and viewable on the Installed Operators page of the OpenShift console) using the images built from this PR.
> Prepare for 1.14 release
